language: "sh"

sudo: "required"

services:
  - "docker"

dist: "trusty"

branches:
  only:
    - "development"

env:
  matrix:
    - "IMAGE=dashboard"
    - "IMAGE=dashboard_nginx"
    - "IMAGE=mcp_client"
    - "IMAGE=mcp_server"
    - "IMAGE=storage_service"
    - "IMAGE=storage_service_nginx"

jobs:
  include:
    - if: type = pull_request
      env: TASK=build

    - if: type = push
      env: TASK=publish

script:
  - make "$IMAGE-$TASK"

notifications:
  email:
    - "wellcomedigitalplatform@wellcome.ac.uk"
