language: "sh"

sudo: "required"

services:
  - "docker"

dist: "trusty"

branches:
  only:
    - "development"

env:
  matrix:
    - "IMAGE=dashboard"
    - "IMAGE=dashboard_nginx"
    - "IMAGE=mcp_client"
    - "IMAGE=mcp_server"
    - "IMAGE=storage_service"
    - "IMAGE=storage_service_nginx"

script:
  >
    if [[ "$TRAVIS_EVENT_TYPE" == "push"]; then
      make "$IMAGE-publish"
    else
      make "$IMAGE-build"
    fi

notifications:
  email:
    - "wellcomedigitalplatform@wellcome.ac.uk"
